name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.REPOSITORY }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
            context: .
            push: true
            platforms: linux/amd64,linux/arm64
            tags: |
              ghcr.io/${{vars.REPOSITORY}/lambert_w:sha-${{ github.sha }}
              ghcr.io/${{vars.REPOSITORY}/lambert_w:branch-${{ github.ref_name }}
              ghcr.io/${{vars.REPOSITORY}/lambert_w:latest
      -
        name: Slim Docker image
        uses: kitabisa/docker-slim-action@v1
        env:
            DSLIM_HTTP_PROBE: "false"  # Disables HTTP probing during slimming
        with:
            target: ghcr.io/${{ vars.REPOSITORY }}/lambert_w:latest  # Target image to slim
            tag: slim  # Suffix for the slimmed image tag

      -
        name: Push slimmed Docker image
        run: |
              docker push ghcr.io/${{ vars.REPOSITORY }}/lambert_w:slim
              
